on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test_Pester_Action:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: A job to run Pester on ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Pester Action
      id: pester
      uses: ./PesterActionV1
      with:
        script: 'tests/sample'
    - name: Upload pester results
      uses: actions/upload-artifact@v2
      with:
        name: pester-results-${{ matrix.os }}
        path: ${{ steps.pester.outputs.logPath }}

    - name: Script is a file
      run: echo '::set-env name=ActionTest_ScriptIsAFile_script::test/sample/sample.tests.ps1'
    - name: Pester Action
      id: pester
      uses: ./PesterActionV1
      with:
        script: 'tests/sample/sample.tests.ps1'

    - name: Pass empty value for script
      run: echo '::set-env name=ActionTest_EmptyValueForScript_script::null'
    - name: Pester Action
      id: pester
      uses: ./PesterActionV1
      with:
        script: ''

    - name: Pass non existent path
      run: echo '::set-env name=ActionTest_NonExistentPath_script::tests/notexists'
    - name: Pester Action
      id: pester
      uses: ./PesterActionV1
      with:
        script: 'tests/notexists'

    - name: Pester version 5.0.0
      run: echo '::set-env name=ActionTest_PesterVersion5_version::5.0.0'
    - name: Pester Action
      id: pester
      uses: ./PesterActionV1
      with:
        version: '5.0.0'

    - name: Pester version 4.10.1
      run: echo '::set-env name=ActionTest_PesterVersion4.10.1_version::4.10.1'

    - name: Pester Action
      id: pester
      uses: ./PesterActionV1
      with:
        version: '4.10.1'

    - name: Pester non existing version
      run: '::set-env name=TestName::ActionTest_NonExistingVersion_version::100.100.100'
    - name: Pester Action
      id: pester
      uses: ./PesterActionV1
      with:
        version: '100.100.100'

    - name: Pester version null
      run: '::set-env name=TestName::ActionTest_PesterVersionNull_version::null'
    - name: Pester Action
      id: pester
      uses: ./PesterActionV1
      with:
        version: ''

    - name: Pester version not number
      run: '::set-env name=ActionTest_PesterVersionNotANumber_version::a.b.c'
    - name: Pester Action
      id: pester
      uses: ./PesterActionV1
      with:
        version: 'a.b.c'

    - name: Log format is NUnitXml
      run: '::set-env name=ActionTest_LogFormatNUnitXml_logformat::NUnitXml'
    - name: Pester Action
      id: pester
      uses: ./PesterActionV1
      with:
        logformat: 'NUnitXml'

    - name: Log format is JUnitXml
      run: '::set-env name=ActionTest_LogFormatJUnitXml_logformat::JUnitXml'
    - name: Pester Action
      id: pester
      uses: ./PesterActionV1
      with:
        logformat: 'JUnitXml'
